"""Create user, build, vote, and perk tables.

Revision ID: c1ee3884a67c
Revises: 
Create Date: 2024-12-04 18:48:58.217394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ee3884a67c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_build_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build_perk',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('perk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], name=op.f('fk_build_perk_build_id_build')),
    sa.ForeignKeyConstraint(['perk_id'], ['perk.id'], name=op.f('fk_build_perk_perk_id_perk')),
    sa.PrimaryKeyConstraint('build_id', 'perk_id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['build.id'], name=op.f('fk_vote_build_id_build')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_vote_user_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('build_perk')
    op.drop_table('build')
    op.drop_table('user')
    op.drop_table('perk')
    # ### end Alembic commands ###
