"""Add folder_path to Build model.

Revision ID: f58a6f89b1e7
Revises: c1ee3884a67c
Create Date: 2024-12-04 19:16:48.079555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58a6f89b1e7'
down_revision = 'c1ee3884a67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('build', schema=None) as batch_op:
        batch_op.drop_column('folder_path')

    # ### end Alembic commands ###
